spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scoa?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-request-size: 200MB #设置最大上传量
      max-file-size: 100MB #设置单文件最大